# Generated by Django 4.0.6 on 2022-10-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_query_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
