# Generated by Django 4.0.6 on 2022-10-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_laptop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptop',
            new_name='material',
        ),
    ]
