# Generated by Django 4.0.6 on 2022-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_material2_material3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='material2',
        ),
        migrations.DeleteModel(
            name='material3',
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('l', 'laptop'), ('c', 'console'), ('d', 'desktop')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
