# Generated by Django 4.0.6 on 2022-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiltlepost', models.CharField(max_length=50)),
                ('writepost', models.CharField(max_length=50050)),
            ],
        ),
    ]
